name: Update Selected Submodules

on:
  workflow_dispatch:
    inputs:
      submodules:
        description: 'Enter submodules to update (comma-separated, e.g., submodule1,submodule2)'
        required: true

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0  # Fetch full history for author details

      - name: Get Committer Details
        id: committer
        run: |
          COMMITTER_NAME=$(git log -1 --pretty=format:'%an')
          COMMITTER_EMAIL=$(git log -1 --pretty=format:'%ae')
          echo "COMMITTER_NAME=$COMMITTER_NAME" >> $GITHUB_ENV
          echo "COMMITTER_EMAIL=$COMMITTER_EMAIL" >> $GITHUB_ENV

      - name: Set Git Author Identity from Triggering User
        run: |
          git config --global user.name "${{ env.COMMITTER_NAME }}"
          git config --global user.email "${{ env.COMMITTER_EMAIL }}"

      - name: Parse Selected Submodules
        id: parse
        run: |
          SUBMODULES="${{ github.event.inputs.submodules }}"
          echo "Selected Submodules: $SUBMODULES"
          echo "SUBMODULES=$SUBMODULES" >> $GITHUB_ENV

      - name: Sync and Update Selected Submodules
        run: |
          for submodule in $(echo "$SUBMODULES" | tr ',' ' '); do
            echo "Updating $submodule..."
            echo "git submodule sync ${submodule}"
            #git submodule sync "$submodule"
            echo "submodule update --init --recursive --remote ${submodule}"
            #git submodule update --init --recursive --remote "$submodule"
          done

      - name: Create New Branch and Push Updated Submodules
        run: |
          # Checkout the develop branch
          git checkout develop
          git pull origin develop

          # Create a new branch for the update
          NEW_BRANCH="update-submodules-${{ github.run_id }}"
          git checkout -b $NEW_BRANCH

          # Test
          touch t2.txt
          echo "test2" > t2.txt

          # Commit and push changes
          git add .
          git commit -m "Update selected submodules: $SUBMODULES"
          #git push origin $NEW_BRANCH
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $NEW_BRANCH
