name: Update Selected Submodules

on:
  workflow_dispatch:
    inputs:
      submodules:
        description: 'Enter submodules to update (comma-separated, e.g., submodule1,submodule2)'
        required: true

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0  # Fetch full history for author details

      - name: Get Committer Details
        id: committer
        run: |
          COMMITTER_NAME=$(git log -1 --pretty=format:'%an')
          COMMITTER_EMAIL=$(git log -1 --pretty=format:'%ae')
          echo "COMMITTER_NAME=$COMMITTER_NAME" >> $GITHUB_ENV
          echo "COMMITTER_EMAIL=$COMMITTER_EMAIL" >> $GITHUB_ENV

      - name: Parse Selected Submodules
        id: parse
        run: |
          SUBMODULES="${{ github.event.inputs.submodules }}"
          echo "Selected Submodules: $SUBMODULES"
          echo "SUBMODULES=$SUBMODULES" >> $GITHUB_ENV

      - name: Sync and Update Selected Submodules
        run: |
          for submodule in $(echo "$SUBMODULES" | tr ',' ' '); do
            echo "Updating $submodule..."
            #git submodule sync "$submodule"
            #git submodule update --init --recursive --remote "$submodule"
          done

      - name: Create and Push New Branch
        run: |
          # Checkout the develop branch
          git checkout develop
          git pull origin develop

          # Create a new branch for the update
          NEW_BRANCH="update-submodules-${{ github.run_id }}"
          git checkout -b $NEW_BRANCH

          # Test
          touch t1.txt
          echo "test1" > t1.txt

          # Commit and push changes
          git add .
          git commit -m "Update selected submodules: $SUBMODULES"
          git push origin $NEW_BRANCH

      - name: Create Pull Request via GitHub API
        run: |
          PR_TITLE="Update Submodules"
          PR_BODY="This PR contains updates to the selected submodules. Please review and merge."
          BASE_BRANCH="develop"
          HEAD_BRANCH=$NEW_BRANCH

          # Create a pull request using GitHub API
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"title\":\"$PR_TITLE\", \"body\":\"$PR_BODY\", \"head\":\"$HEAD_BRANCH\", \"base\":\"$BASE_BRANCH\"}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls"
